import {
  SearchOutlined,
  BellFilled,
  CommentOutlined,
  HomeFilled,
  GlobalOutlined,
  UserOutlined,
  CompassFilled,
  MoreOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  EditFilled,
  CheckOutlined,
  InfoCircleFilled,
  DislikeOutlined,
  LikeOutlined,
  DislikeFilled,
  LikeFilled,
  CloudUploadOutlined,
  PlusCircleFilled,
  PlusOutlined,
  FilterOutlined,
  SaveFilled
} from "@ant-design/icons";

import { Users, MapPin, BarChart2, XCircle } from "react-feather";

export {
  SearchOutlined,
  BellFilled,
  CommentOutlined,
  HomeFilled,
  GlobalOutlined,
  UserOutlined,
  CompassFilled,
  MoreOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  EditFilled,
  Users,
  MapPin,
  CheckOutlined,
  InfoCircleFilled,
  BarChart2,
  DislikeOutlined,
  LikeOutlined,
  DislikeFilled,
  LikeFilled,
  CloudUploadOutlined,
  PlusCircleFilled,
  PlusOutlined,
  FilterOutlined,
  XCircle,
  SaveFilled
};
